### ISSUE TITLE
does it support h264 + g711a ?

### ISSUE THREAD

**Issue by rockcarry** [Rolinh/libgwavi#8]
I want save h264 video and g711a audio into avi file.
does libgwavi support ?

**Comment by rolinh** [comment]
Hi @rockcarry,

H264: yes.
g711a audio: probably not because audio support is not in a good shape.

I'm happy to merge PRs that fix the audio part though :)

**Comment by rockcarry** [comment]
I changed the code:
        gwavi->stream_header_a.codec[0] = 'G';
        gwavi->stream_header_a.codec[1] = '7';
        gwavi->stream_header_a.codec[2] = '1';
        gwavi->stream_header_a.codec[3] = '1';
        gwavi->stream_format_a.format_type = 6;

if works fine for g711a.
